name: ActivaWars
version: ${project.version}
main: nl.activakingdoms.wars.Main
api-version: 1.13
authors: [Jake_O]
description: De plugin voor het oorlog-systeem van ActivaKingdoms
website: www.activakingdoms.nl
depend: [LuckPerms]
commands:
  war:
    description: The main command for the ActivaWars plugin.
    usage: /war

permissions:
  activawars.*:
    description: Wildcard permission
    default: op
    children:
      activawars.war: true

  activawars.war:
    description: The permission to use the main command.
    default: true
    children:
      activawars.war.setup: false
      activawars.war.settings: false
      activawars.war.addteam: false
      activawars.war.removeteam: false
      activawars.war.addplayer: false
      activawars.war.removeplayer: false
      activawars.war.setcolor: false

  activawars.war.addteam:
    description: Usage of /war addteam
    default: op
  activawars.war.removeteam:
    description: Usage of /war removeteam
    default: op

  activawars.war.addplayer:
    description: Usage of /war addplayer
    default: op
  activawars.war.removeplayer:
    description: Usage of /war removeplayer
    default: op

  activawars.war.setup:
    description: Usage of /war setup
    default: op
  activawars.war.setcolor:
    description: Usage of /war setcolor
    default: op
  activawars.war.settings:
    description: Usage of /war settings
    default: op
    children:
      activawars.war.settings.allowrespawn: false
      activawars.war.settings.friendlyfire: false

  activawars.war.settings.*:
    description: Wildcard permission for editing settings
    default: op
    children:
      activawars.war.settings.allowrespawn: true
      activawars.war.settings.friendlyfire: true


  activawars.war.settings.allowrespawn:
    description: Allows editing of setting "Allow Respawn"
    default: op
  activawars.war.settings.friendlyfire:
    description: Allows editing of setting "Friendly-fire"
    default: op

